### ISSUE TITLE
How to use this pysfm?

### ISSUE THREAD

**Issue by realhire** [alexflint/pysfm#1]
Hi,
I am new to use BA to optimize the sfm. I am so glad to find your pysfm with BA.
I have learned quite a lot about how to build 3D model from mutil-views, and want to learn how to optimize them. 

I found there are several files related to BA, so  I am confuesed.

Could you tell me how to use these files, if I have got 3D-2D pairs and camera matrixs??

Thanks,

realhire

**Comment by alexflint** [comment]
Unfortunately this project is still incomplete. Try taking a look at https://github.com/alexflint/pysfm/blob/master/test_bundle.py
