### ISSUE TITLE
How to use pysfm?

### ISSUE THREAD

**Issue by jahdiel** [alexflint/pysfm#2]
Hi, 

I am using python for implementing a monocular visual odometry project, and wish to implement a bundle adjustment algorithm to it. Is it possible for someone to explain how to use this project, if obe has 3D points, corresponding 2D image coordinates and the camera matrices. Thanks.

**Comment by alexflint** [comment]
Unfortunately this project is still not complete. Try taking a look at https://github.com/alexflint/pysfm/blob/master/standalone/optimize_camera.py
